name: dart_mappable_example
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dart_mappable: ^4.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3

dependency_overrides:
  preact_signals:
    path: ../../packages/preact_signals
  signals: 
    path: ../../packages/signals
  signals_core:
    path: ../../packages/signals_core
  signals_flutter:
    path: ../../packages/signals_flutter
  signals_lint:
    path: ../../packages/signals_lint

flutter:
