name: signals_dart_examples
description: Pure dart examples using signals
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.3.0

dependencies:
  collection: ^1.18.0
  sqlite_async: ^0.6.1
  test: ^1.25.2

dev_dependencies:
  lints: ^3.0.0

dependency_overrides:
  preact_signals:
    path: ../../packages/preact_signals
  signals: 
    path: ../../packages/signals
  signals_core:
    path: ../../packages/signals_core
  signals_flutter:
    path: ../../packages/signals_flutter
  signals_lint:
    path: ../../packages/signals_lint
