name: signals_core
description: Reactivity made simple. Do more by doing less.
version: 1.0.6
repository: https://github.com/rodydavis/signals.dart
homepage: https://rodydavis.github.io/signals.dart
documentation: https://rodydavis.github.io/signals.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

topics:
  - signal
  - reactive
  - state
  - signals
  - rx
