name: shopping_cart
description: Shopping cart example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lite_ref: ^0.7.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

dependency_overrides:
  preact_signals:
    path: ../../packages/preact_signals
  signals: 
    path: ../../packages/signals
  signals_core:
    path: ../../packages/signals_core
  signals_flutter:
    path: ../../packages/signals_flutter
  signals_lint:
    path: ../../packages/signals_lint

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
