name: html_todo_app
description: Todo HTML web app with signals
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.3.0

dependencies:
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  lints: ^3.0.0

dependency_overrides:
  preact_signals:
    path: ../../packages/preact_signals
  signals: 
    path: ../../packages/signals
  signals_core:
    path: ../../packages/signals_core
  signals_flutter:
    path: ../../packages/signals_flutter
  signals_lint:
    path: ../../packages/signals_lint

scripts:
  dev: webdev serve
