name: get_it_signals_example
description: get_it + signals
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^13.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

dependency_overrides:
  preact_signals:
    path: ../../packages/preact_signals
  signals: 
    path: ../../packages/signals
  signals_core:
    path: ../../packages/signals_core
  signals_flutter:
    path: ../../packages/signals_flutter
  signals_lint:
    path: ../../packages/signals_lint

flutter:
  uses-material-design: true
